version: '3.7'

services:
  server:
    container_name: server-pro4
    build:
      context: ./
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - 3333:3333
    env_file:
      - .env
    environment:
      - IN_CONTAINER=true
      # - DEBUG=*
      - PORT=3333
      - DATABASE_URL=postgresql://pro4:pro4@pg-pro4:5432/pro4?schema=public

    # Connection URL: postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA
    volumes:
      - './:/app:delegated'
      - '/app/node_modules'
#     depends_on:
#       - pg-pro4

#   pg-pro4:
#     container_name: pg-pro4
#     image: postgres:13.2-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=pro4
#       - POSTGRES_PASSWORD=pro4
#       - POSTGRES_DB=pro4
#     volumes:
#       - './db/data:/var/lib/postgresql/data'

# volumes:
#   db:
